### ISSUE TITLE
見に覚えのないコミットが生成されている

### ISSUE THREAD

**Issue by bgpat** [kstm-su/es-syllabus-web#4]
<img width="495" alt="image" src="https://user-images.githubusercontent.com/6045753/39065442-c5666768-450c-11e8-8e5d-0cea7b7ad596.png">

**Comment by fono09** [comment]
あ、さては公開サーバーのgitの設定変えずにコミットしたな

**Comment by ugwis** [comment]
force push して戻します

**Comment by ugwis** [comment]
直しました
<img width="939" alt="screen shot 2018-04-21 at 19 20 49" src="https://user-images.githubusercontent.com/914815/39083081-2f8aa334-4599-11e8-9de7-fe1a3ba82fb0.png">

**Comment by bgpat** [comment]
👍
